services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  # Captura los emails de prueba
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"   # UI web
      - "1025:1025"   # SMTP

  publisher:
    build: ./Publisher
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      AMQP_URL: amqp://rabbitmq

  consumer:
    build: ./Consumer
    depends_on:
      rabbitmq:
        condition: service_healthy
      mailhog:
        condition: service_started
    environment:
      AMQP_URL: amqp://rabbitmq
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_FROM: no-reply@mi-tienda.test
